[package]
name = "rum"
version = "0.1.0"
edition = "2021"
author = "Yann Youbi <yann-ybi@uri.edu>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"

[profile.release]
lto = true